version: "3"

services:
  docker:
    environment:
    - DOCKER_TLS_CERTDIR=/certs
    image: docker:dind
    ports:
    - "2376:2376"
    privileged: true
    volumes:
    - certs:/certs/client
    - jenkins-home:/var/jenkins_home

  jenkins:
    build: .
    depends_on:
    - docker
    environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - DOCKER_CERT_PATH=/certs/client
    - DOCKER_HOST=tcp://docker:2376
    - DOCKER_TLS_VERIFY=1
    ports:
    - "8080:8080"
    - "50000:50000"
    volumes:
    - certs:/certs/client:ro
    - jenkins-home:/var/jenkins_home

volumes:
  certs:
  jenkins-home:
